### ISSUE TITLE
Share slackarchive-website repo

### ISSUE THREAD

**Issue by patcon** [dutchcoders/slackarchive#1]
Yaaaaay! :tada: :tada: :tada: 

So excited about this!

So that we can help change the front-facing website to better communicate the changing nature of the project (and the different ways people can engage or contribute to it), would it be possible to open source the front-end too, so that we can help migrate text and positioning of the hosted product? No pressure, just want to start thinking on how we can improve that

No pressure, and as always, curious your thoughts :)

**Comment by nl5887** [comment]
Awesome!

The SlackArchive web frontend has its own repository -> https://github.com/dutchcoders/slackarchive-app.
