### ISSUE TITLE
Should the data be available immediately after launch?

### ISSUE THREAD

**Issue by strelov1** [dutchcoders/slackarchive#12]
Already passed the day after the launch, but the data never shows in the web interface.
The bot log shows that it receives data

**Comment by strelov1** [comment]
I should have invited the bot to the channel.
https://github.com/dutchcoders/slackarchive/blob/master/api/api.go#L364

**Comment by patcon** [comment]
@strelov1 might you be able to suggest where this could be best documented to help the next person travelling your path? :) Thanks for your comments regardless!
