### ISSUE TITLE
Redirect https://slackarchive.io to https://github.com/dutchcoders/slackarchive

### ISSUE THREAD

**Issue by yanokwa** [dutchcoders/slackarchive#17]
https://slackarchive.io points to https://github.com and I think it'd be nicer to link to https://github.com/dutchcoders/slackarchive

@nl5887 I think you are the one who can fix this one.

**Comment by peterrus1** [comment]
for me it already does.

**Comment by yanokwa** [comment]
Agreed that it's fixed now.
