### ISSUE TITLE
Missing docker-compose.yml

### ISSUE THREAD

**Issue by giovannibonetti** [dutchcoders/slackarchive#2]
Hi!
Thank you for open-sourcing this project. I tried it out but realized the `docker-compose.yml` file is missing. Can you please include it with the project?

**Comment by psifertex** [comment]
Looks like it's there? 
https://github.com/dutchcoders/slackarchive-docker/blob/master/docker-compose.yaml

**Comment by nl5887** [comment]
Exactly, we decided to put all complete docker compose in a separate repository.
