### ISSUE TITLE
Lack of information in title and readme.

### ISSUE THREAD

**Issue by Nklya** [dutchcoders/slackarchive#5]
Hello.

I found it difficult to understand what for this repository is.

I think it would be better if you add a link to official site http://slackarchive.io in the title and Readme.
And a little project description at the beginning of Readme.

**Comment by nl5887** [comment]
Sure, the slackarchive.io will soon be replaced with a redirect to the this repository.

**Comment by Nklya** [comment]
Ok, thanks 👍 
I think I can close this issue.

**Comment by patcon** [comment]
Hi Remco! Might you be willing to put out a call-for-maintainers, and see if a community of people might be interested in adopting the domain and hosting a community service there? Perhaps the kubernetes community (or another large one that received a lot of value from the service) might be interested to help run it :)

No pressure though. That could be more work than you can support, which everyone would totally understand
