### ISSUE TITLE
some better explanation of the various tokens / keys required ?

### ISSUE THREAD

**Issue by paulwilton** [dutchcoders/slackarchive#8]
any chance you can update README with some more info on what the various tokens/keys need to be set to.. in the yaml files  - their purpose
thanks!

**Comment by jaredthecoder** [comment]
@paulwilton I recommend starting with the https://github.com/dutchcoders/slackarchive-docker repo. That one is much more clear as to where to set tokens.

**Comment by paulwilton** [comment]
the updated README is much clearer now - thanks!
